  
name: ml
dependencies:
  - python=3.6.5
  - matplotlib
  - nose
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - python-dateutil
  - pip
  - seaborn
  - pip:
    - datetime
    - mlrose-hiive
    - seaborn